jdk:
- oraclejdk8
language: java
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: dniel-github
    token:
      secure: HU5a7nqsOZq+h/lMMclO6PBX9xKvOJqL+T2yPwfeB3W6utVzlWVyqJNoeouWVI/FAJ26ak9BuOu2nMxZgFSU8qoTrJayxaUkJPFhpHRCEblZU+pSGOHwIeM1K0dy7je1QsBiA5MF1cjd9i39IybL92q7axvGAUyiRyFSYnRjXyH1aTIEIWq8TVs77UjM3JU5jq4yryL/vEqR8bxGGqEP9Mf6zQqFjF0wKTnxyDtGwycQ0NdnmuDb/r7NnvwYIbaQ22Dfve8KS82c3STVm2uUwyT8R6Gi/mp2Ub2s9jPs0MC1BmKhHyABx4KQ4vetx2ZsFqGbo6lWR6Pv7rfNexdX9ThkOJkNEaa6oqkxsumvhi183zzGkZR7fB7O1HTx/rJzJQBGvme0F3HPJkHdrwJqKWDACWhg8WWFDGMJt9RGBSvPIjzqSTsMbidKYg9GqFLkPu2dP4x9w2oZGRX4fu0Tl8q9GXhCnVqc08UzvPBOwVkzILtdFCevHiZLRe2QAmIPSZdOBdJV+uw6PQwmtN1YlhTuSCQ5Y+Z57wbNs0Gx8TgjWKr/mOTZZT0UBKO+jdRuxXJ5jWqcHm4AZU/GfEpaui3E6vmGVJjK5+vHQqwctxAXdGf15KZD6sJtUKOXImH50a4ZO1CZiZ7M0fF0vQhnSK4WnV8lOziXqkLm4JNqNe0=

services:
- docker

before_install:
- export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
- export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$BRANCH"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsha1=$TRAVIS_TAG -Dchangelist=$BRANCH

deploy:
- provider: script
  script:
  - docker build -t dniel/forwardauth .
  - docker tag dniel/forwardauth dniel/forwardauth:$TRAVIS_TAG
  - docker tag dniel/forwardauth dniel/forwardauth:$BRANCH
  on:
    all_branches: true
- provider: script
  script:
  - docker build -t dniel/forwardauth .
  - docker tag dniel/forwardauth dniel/forwardauth:$TRAVIS_TAG
  - docker tag dniel/forwardauth dniel/forwardauth:$BRANCH
  - docker tag dniel/forwardauth dniel/forwardauth:latest
  on:
    branch: master

