if: tag IS blank
jdk:
  - oraclejdk8
language: java
install: true
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: dniel-github
    token: "$SONAR_TOKEN"
services:
  - docker
before_script:
  - export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - export COMMIT_TIME=$(git log -1 --pretty=format:%ct|date +"%m%d%Y-%H%M")
  - export APP_VERSION=$COMMIT_TIME-$TRAVIS_TAG
  - echo "$TRAVIS_TAG $TRAVIS_COMMIT $BRANCH $COMMIT_TIME"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsha1=$APP_VERSION -Dchangelist=$BRANCH
after_success:
  - docker build -t dniel/forwardauth .
deploy:
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_release.sh"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_feature.sh"
    on:
      all_branches: true
      if: $BRANCH != "master"
notifications:
  slack:
    rooms:
      secure: izNrP9LY8rLdBiQtAZJUPMSnVGUNDiw3FQ2LKydk2ct0jDGVEw6ztoiA9bmF+IoLxTtKLo1nk/2LUCT9D5regNNQ7/MR3K5r2oOstXJKwNhQlOko/g+DYcc+cRwkcD+e1drEJxjw4FO71JaAAUAMjv2x7nAwlqnDQz1s6eh8ZhYvl554+kAF1ha0u++KabXn8cUSDlJs1qOhQAjrjuudAbXw2xgGIKr/Wx0EgtrohgqsRTWjuTHThYZE3+10aDaQ2/NbrSrdVMo5o3PJJW8bv4n2crCiqFD5r6c7Zhx5TSJXbcDjk3pttsz0n6mUrhQ0snVc167IwYW4AdxyEbF+NTKqh3RyeLbkLi+CaujE3/VbMW93QYoa+ckMhZZXDlghBuiW4hRI1c9CDqjcb9uWOffQuHdceDn4rLs4UUeGZ09bxL2vj5qC9mKsU30TZFEXKSyGbFzYC7VgM1eCklvUvxpUvxwPm5mbrqMuJdvueUrpp5CrY5mmEvOYJZxMVLhizATBIRUDQqHtJ9CVHGNntsHnBxG8K+aToQiGHwyclekLTOGJzeaMt9seplTCtdoeCidGnX8NsZnbboOIi4Rw4GWupA1WgLJJkB9s6IZbYs3i2RT1UCcJGMX5C+6SPvn+gDcJYxLM1iCYl52UH6nqSzULYYdsoADYxelOxuGpWr4=
    on_success: always
    on_failure: always
    template:
      - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
        for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
      - 'Execution time: *%{duration}*'
      - 'Message: %{message}'
env:
  global:
    secure: iHN7Ig4AZkNk/nNMSlpGoMFDCGNQJ74rbEzWT1p+AKQLQnxeadXDG6SMIaOcZtcM74C6lHg8R26j1dMVf1hHfazEThUhFpV6QIewGMHVzUHNov/pwpjEV9nObBD/0c6jgi0eKim5ImWZwiUpIrp9Gd7KhnQz9o75nT+cRAf/Gt/K6WJGZ3Uo5o3Ltld/3csfBv/eUtIO9VAgPwdkxSrgkZr2SwdplpspuApGlqNtHfHK3rCdhtGyS+HRfslgIG+DRYwheAEfXwXlcksAKDzL4A5aRNg5/hrMQ8hP94vJCMzu8f7ZpiJLnYtzbh8v4AG9d1GzFg1lCBG7z5hbhXfjevqQ1VkaMISlakUQCfa5vWNiG4ydEplipn4ca9DTbagmKqi6yaOZGw51ipA7BiNo7g2zJRYTPPlWjei0REj8ijqicmiQrrvnIcLRjqGh+WJZ5Yne5wOCs6gR//xW+a8WWz8tbTqd/UoGfYeHIEe33XPitKiAbvhxdQzKMNu61sGbllKUC7Of7GKP+Mx8W5s+4QQZHR8H0GJqwr0LGHx4t5qUATHhAGdJQZLivFOXOxbnSmqgG3dhRbnEMHYEWixHH+QU5dqn1BCNWS7Lv8m1/C+1ZA6HFmScNzQwcqu7EWBpxnOoMWx292Sbj8jG8S1QEuAOSVR8H8yrK5RgV5XRr1c=
