jdk:
  - oraclejdk8
language: java
install: true
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: dniel-github
    token: $SONAR_TOKEN

services:
  - docker

before_script:
  - export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$BRANCH"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsha1=$TRAVIS_TAG -Dchangelist=$BRANCH

after_success:
  - docker build -t dniel/forwardauth .

deploy:
  # deploy release if branch is master
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy_release.sh
    on:
      branch: master

  # deploy feature if branch is something other than master
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy_feature.sh
    on:
      all_branches: true
      if: $BRANCH != "master"
