jdk:
- oraclejdk8
language: java
install: true
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: dniel-github
    token:
      secure: "ql9vJmGbnNtmziPhltLSMuBJpb92IoJiO6rz+4qvI+jiP5jJpQBBH6mfgjylVLGaBX/pFlBIffSa8Tx7LRGWXaovISVneZbMGpvLRN27MKikLEXCNzdtBEPXepcioIVo6GMeliR0x6cl855IB+0iZ982U2OpiP5e5+SDCLuyIR7fJUWw7VIfYl8UgORcemrxcJ8tM/ErIkZG53C4K5Uv6m70ctIXV0TFbG+CMF6bpTRcrDNzgZJPQkTR8MK1qUGP6Osd0q5XndvZaf6mw66oVZUQN4CaZawy7SC2X2vkW9drkQNMSdHkJzaSTr1wY9c20kEB4WzFmNddCVbIbr4449oRRWtnCC5PomeAzeAcNDdrbCqSmIkZb3Xb0mEZKDFqQoPXZS+6e8rwFsw/cUu+v63WkBj8F2L1evuI6aQ6tjISYDwgL9p0p3IRsO3qjfE1nJJGkhA4GtW1t2WGfR60eGILkT0Dn1Tc+hWP0KM/zY4vfulvuDN4in5A2aLqN2SYABz8aD8PJTdxn5a7B2H4hVXheJIq1veseK//O10pBVTcB7mNK/3aLqy1QcxKZxZc/t9Nd7k9gmihZ6c7AC/Ki+GyXdKbrBvW/yLHOzi5YDRWg1C3pNVDEAg6/ju9I1uaHDn+jRLB1CtZQJTM+EgVf0NrVbyt2Jd8TKXDRz2D6e0="

services:
- docker

before_install:
- export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
- export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$BRANCH"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsha1=$TRAVIS_TAG -Dchangelist=$BRANCH -Dsonar.login=$SONAR_TOKEN

deploy:
- provider: script
  script:
  - docker build -t dniel/forwardauth .
  - docker tag dniel/forwardauth dniel/forwardauth:$TRAVIS_TAG
  - docker tag dniel/forwardauth dniel/forwardauth:$BRANCH
  on:
    all_branches: true
- provider: script
  script:
  - docker build -t dniel/forwardauth .
  - docker tag dniel/forwardauth dniel/forwardauth:$TRAVIS_TAG
  - docker tag dniel/forwardauth dniel/forwardauth:$BRANCH
  - docker tag dniel/forwardauth dniel/forwardauth:latest
  on:
    branch: master

