jdk:
  - oraclejdk8
language: java
cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$BRANCH"

install:
  - chmod +x mvnw
  - mvn -N io.takari:maven:wrapper

script:
  - ./mvnw clean install -Dsha1=$TRAVIS_TAG -Dchangelist=$BRANCH -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  - docker build -t dniel/forwardauth .
  - docker tag dniel/forwardauth dniel/forwardauth:$TRAVIS_TAG