jdk:
  - oraclejdk8
language: java
install: true
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: dniel-github
    token: "$SONAR_TOKEN"
services:
  - docker
before_script:
  - export TRAVIS_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT" "$BRANCH"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsha1=$TRAVIS_TAG -Dchangelist=$BRANCH
after_success:
  - docker build -t dniel/forwardauth .
deploy:
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_release.sh"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: "./.travis/deploy_feature.sh"
    on:
      all_branches: true
      if: $BRANCH != "master"

notifications:
  slack:
    secure: izNrP9LY8rLdBiQtAZJUPMSnVGUNDiw3FQ2LKydk2ct0jDGVEw6ztoiA9bmF+IoLxTtKLo1nk/2LUCT9D5regNNQ7/MR3K5r2oOstXJKwNhQlOko/g+DYcc+cRwkcD+e1drEJxjw4FO71JaAAUAMjv2x7nAwlqnDQz1s6eh8ZhYvl554+kAF1ha0u++KabXn8cUSDlJs1qOhQAjrjuudAbXw2xgGIKr/Wx0EgtrohgqsRTWjuTHThYZE3+10aDaQ2/NbrSrdVMo5o3PJJW8bv4n2crCiqFD5r6c7Zhx5TSJXbcDjk3pttsz0n6mUrhQ0snVc167IwYW4AdxyEbF+NTKqh3RyeLbkLi+CaujE3/VbMW93QYoa+ckMhZZXDlghBuiW4hRI1c9CDqjcb9uWOffQuHdceDn4rLs4UUeGZ09bxL2vj5qC9mKsU30TZFEXKSyGbFzYC7VgM1eCklvUvxpUvxwPm5mbrqMuJdvueUrpp5CrY5mmEvOYJZxMVLhizATBIRUDQqHtJ9CVHGNntsHnBxG8K+aToQiGHwyclekLTOGJzeaMt9seplTCtdoeCidGnX8NsZnbboOIi4Rw4GWupA1WgLJJkB9s6IZbYs3i2RT1UCcJGMX5C+6SPvn+gDcJYxLM1iCYl52UH6nqSzULYYdsoADYxelOxuGpWr4=
