# This is an example docker-compose file.
# It will not run without configuring a working /config/traefik.toml and /config/application.yaml
# Have a look at the files in the example directory as a starting point how to create the two files.

traefik:
  image: traefik:v1.7.11-alpine
  ports:
    - 80:80
    - 8081:8081
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config/traefik.toml:/traefik.toml

whoami:
  image: containous/whoami
  labels:
    - "traefik.frontend.rule=Host:whoami.example.test"
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.auth.forward.address=http://auth.example.test/authorize"
    - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

auth:
  image: dniel/forwardauth:add.travis.ci.build.file
  ports:
    - 8080:8080
  labels:
    - "traefik.frontend.rule=Host:auth.example.test"
    - "traefik.enable=true"
    - "traefik.port=8080"
  volumes:
    - ./config/application.yaml:/config/application.yaml

www:
  image: dniel/blogr-www
  labels:
    - "traefik.frontend.rule=Host:www.example.test"
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.auth.forward.address=http://auth.example.test/authorize"
    - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
