# This is an example docker-compose file.
# It will not run without configuring a working /config/traefik.toml and /config/application.yaml
# Have a look at the files in the example directory as a starting point how to create the two files.
version: '2.4'
services:
  traefik:
    image: traefik:v1.7.9-alpine
    ports:
      - 80:80
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik
    labels:
      - "traefik.frontend.rule=Host:traefik.example.test"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.auth.forward.address=http://auth.example.test/authorize"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
      - "traefik.frontend.errors.common.status=401,403,404,429,500,503"
      - "traefik.frontend.errors.common.backend=errors-traefik1"
      - "traefik.frontend.errors.common.query=/{status}.html"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.example.test"
      - "traefik.enable=true"
      - "traefik.frontend.auth.forward.address=http://auth.example.test/authorize"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  errors:
    image: guillaumebriday/traefik-custom-error-pages
    ports:
      - 80

  auth:
    image: dniel/forwardauth
    ports:
      - 8080:8080
    mem_limit: 512m
    mem_reservation: 256m
    labels:
      - "traefik.frontend.rule=Host:auth.example.test"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.errors.common.status=401,403,404,429,500,503"
      - "traefik.frontend.errors.common.backend=errors-traefik1"
      - "traefik.frontend.errors.common.query=/{status}.html"
    volumes:
      - ../../config/application.yaml:/config/application.yaml

  www:
    image: dniel/blogr-www
    labels:
      - "traefik.frontend.rule=Host:www.example.test"
      - "traefik.enable=true"
      - "traefik.frontend.auth.forward.address=http://auth.example.test/authorize"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
