# This is an example docker-compose file.
# It will not run without configuring a working /config/traefik.toml and /config/application.yaml
# Have a look at the files in the example directory as a starting point how to create the two files.

traefik:
  image: traefik:v2.0-alpine
  ports:
    - 80:80
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml

whoami:
  image: containous/whoami
  labels:
    - "traefik.http.routers.whoami.rule=Host(`whoami.example.test`)"

auth:
  image: dniel/forwardauth
  ports:
    - 8080:8080
  labels:
    - "traefik.http.routers.auth.rule=Host(`auth.example.test`)"
  volumes:
    - ../../config/application.yaml:/config/application.yaml

www:
  image: dniel/blogr-www
  labels:
    - "traefik.http.routers.www.rule=Host(`www.example.test`)"
    #- "traefik.http.routers.www.middlewares=ForwardAuth"