[global]
debug = true

[entrypoints]
  [entrypoints.http]
     address = ":80"

################################################################
# Middlewares
################################################################
[http.middlewares]
  [http.middlewares.forwardauth.ForwardAuth]
    address = "http://host.docker.internal:8080/authorize"
    authResponseHeaders =  ["Authorization", "X-FORWARDAUTH-NAME", "X-FORWARDAUTH-SUB", "X-FORWARDAUTH-EMAIL"]

[providers]
  # Enable File Provider.
  #[providers.file]
  #  filename = "/etc/traefik/traefik2-file.toml"
  #  watch = true

  # Enable Docker Provider.
  [providers.docker]
    filename ="/etc/traefik/traefik2-docker.toml"
