# If you start the application with docker-compose up, and want to use
# Traefik auto discovery of containers running, then you could just add something like this instead.
#
# [docker]
# endpoint = "unix:///var/run/docker.sock"
# watch = true
# exposedbydefault = false

[global]
debug = true

[entrypoints]
  [entrypoints.http]
     address = ":80"

[providers]

  ################################################################
  # File Provider
  ################################################################
  # Enable File Provider.
  [providers.file]
    filename = "/etc/traefik/traefik2-file.toml"
    watch = true
