[global]
debug = true

[API]
  Dashboard = true
  [API.Statistics]
   RecentErrors = 42

[entrypoints]
  [entrypoints.http]
     address = ":80"

################################################################
# Middlewares
################################################################

[providers]
  # Enable File Provider.
  #[providers.file]
  #  filename = "/etc/traefik/traefik2-file.toml"
  #  watch = true

  # Enable Docker Provider.
  [providers.docker]
    filename ="/etc/traefik/traefik2-docker.toml"
