################################################################
# Docker Provider
################################################################
watch = true
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = true