################################################################
# File Provider
################################################################

[http]
  ################################################################
  # Middlewares
  ################################################################
  [http.middlewares]
      [http.middlewares.forwardauth.ForwardAuth]
        address = "http://host.docker.internal:8080/authorize"
        authResponseHeaders =  ["Authorization", "X-FORWARDAUTH-NAME", "X-FORWARDAUTH-SUB", "X-FORWARDAUTH-EMAIL"]


  ################################################################
  # Routers
  ################################################################
  [http.routers]
    [http.routers.router0]
      entrypoints = ["http"]
      service = "whoami"
      rule = "Host(`whoami.example.test`)"

    [http.routers.router1]
      entryPoints = ["http"]
      priority = 9999999
      service = "oauth"
      rule = "Host(`auth.example.test`)"


  ################################################################
  # Services
  ################################################################
  [http.services]
    [http.services.whoami]
      [http.services.whoami.LoadBalancer]
        [[http.services.whoami.LoadBalancer.Servers]]
          url = "http://host.docker.internal:8000"
          weight = 1

    [http.services.oauth]
      [http.services.oauth.LoadBalancer]
        [[http.services.oauth.LoadBalancer.Servers]]
          url = "http://host.docker.internal:8080"
          weight = 1