[global]
debug = false

[API]
  Dashboard = true
  [API.Statistics]
   RecentErrors = 42

[entrypoints]
  [entrypoints.http]
     address = ":80"

[providers]
  # Enable Docker Provider.
  [providers.docker]
    filename ="/etc/traefik/traefik2-docker.toml"
