[global]
debug = true

[entrypoints]
  [entrypoints.http]
     address = ":80"

[providers]
  # Enable File Provider.
  #[providers.file]
  #  filename = "/etc/traefik/traefik2-file.toml"
  #  watch = true

  # Enable Docker Provider.
  [providers.docker]
    filename ="/etc/traefik/traefik2-docker.toml"
